/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Cgu: () => import('#controllers/cgu_controller'),
  guides: {
    CreateGuides: () => import('#controllers/guides/create_guides_controller'),
    DeleteGuide: () => import('#controllers/guides/delete_guide_controller'),
    EditGuide: () => import('#controllers/guides/edit_guide_controller'),
    ShowGuide: () => import('#controllers/guides/show_guide_controller'),
    ShowGuides: () => import('#controllers/guides/show_guides_controller'),
  },
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Home: () => import('#controllers/home_controller'),
  ShowVideos: () => import('#controllers/show_videos_controller'),
}
