/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GuideSchema extends BaseModel {
  static $columns = ['createdAt', 'githubRawUrl', 'id', 'slug', 'thumbnail', 'title', 'updatedAt'] as const
  $columns = GuideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare githubRawUrl: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare slug: string
  @column()
  declare thumbnail: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'id', 'name', 'nickName', 'providerId', 'providerType', 'token', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare nickName: string | null
  @column()
  declare providerId: string
  @column()
  declare providerType: string
  @column()
  declare token: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
