name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push OCI image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ctrlfdocker/installerwindows
          tags: |
            type=sha,prefix=

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  execute_commands_via_ssh:
    name: Pull the image and restart the container
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_API_TOKEN }}" localhost:8080/v1/update
