name: CD

on:
  push:
    branches:
      - main

jobs:
  push_image_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the repo
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ctrlfdocker/installerwindows
          flavor: latest=true
          tags: |
            type=sha,prefix=
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4.1.0
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  execute_commands_via_ssh:
    name: Pull latest docker image and start up the application with Docker Compose
    runs-on: ubuntu-latest
    needs: push_image_to_docker_hub
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            systemctl --user stop container-iw-front.service
            podman pull --authfile /etc/containers/auth.json docker.io/ctrlfdocker/installerwindows:latest
            systemctl --user start container-iw-front.service